/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: aa39f0dd62a7dc5eddccfff83bd1606d)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	STATIC: Fetcher;
	APP_NAME: "风筝单词";
	ADMIN_PASSWORD: string;
	SESSION_SECRET: string;
	AUDIO_ONLINE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "ADMIN_PASSWORD" | "SESSION_SECRET" | "AUDIO_ONLINE">> {}
}
